### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by NaaaRiii** [NaaaRiii/furima-31135#9]
# URL
https://furima-31135.herokuapp.com/

# Basic認証のIDとパスワード
ID:NaaaR
パスワード
4869

# 出品者用のメールアドレスとパスワード
email:sample@sample.com
パスワード:na1234

# 購入者用のメールアドレスとパスワード
email:sample1@sample.com
パスワード:ma1234

# 購入用カードの番号・期限・セキュリティコード
カード番号:4242424242424242
期限:3月23年
セキュリティコード:123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]

- [ ]売却済みの商品以外は、画像上に「sold out」の文字が表示されないようにしましょう！
現状、出品してすぐの商品も「sold out」が表示されています。

- [ ] エラーハンドリングができているようにしましょう！（エラーハンドリング=適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）
現状、商品編集時に空欄の項目があっても編集が完了してしまいます。

- [ ] 必要な情報を適切に入力すると、商品の購入ができるようにしましょう！
現状、購入するボタンを押しても購入ページに遷移できません。


※上記により、購入機能について挙動確認が行えないため、次回以降に確認いたします。
※ご提出前に、Trelloの「実装の条件」を参考に、自身のフリマアプリの機能が、デプロイ後の本番環境で問題なく動作しているか確認してください。

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂いたところ、一部前回から引き続いての不備が見受けられましたので修正をお願いします！
### [修正箇所]

- [ ] エラーハンドリングができているようにしましょう！（エラーハンドリング=適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）
**現状、商品編集時に商品説明欄が空欄であっても編集が完了してしまいます。**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
